### PR TITLE
Merge null safety branch to master

### PR DESCRIPTION
**Pull request by mit-mit**
From chatting with @jakemac53, the recommendation is to move null safety to the master branches now that we're prepping for beta.

### CODE REVIEW

**Comment by mit-mit** [comment]
Also, once this lands, would be great to roll this to the SDK DEPS.

**Comment by dcharkes** [comment]
Just to double check, do we want to release package versions through master, and stop maintaining a legacy branch? (Anyone wanting to use new features that get landed, for example #61, would have to opt in to NNBD?)

**Review by dcharkes — APPROVED** [review]

**Comment by jakemac53** [comment]
Note that users don't have to update to NNBD to use new features, but they do have to update to the >=2.12.x sdk

**Comment by dcharkes** [comment]
2.12 is only on beta right? not on stable?

I was under the impression we only publish dev releases for packages with SDK constraints that are a beta or dev branch. If we have a different policy with the NNBD migration, that is fine by me.

**Comment by jakemac53** [comment]
> I was under the impression we only publish dev releases for packages with SDK constraints that are a beta or dev branch.

This _is_ a pre-release, we just are using a more specific `-nullsafety` name for it instead of `-dev`

**Comment by dcharkes** [comment]
I see, so master branch, but `-nullsafety.x` version name. 👍

**Comment by dcharkes** [comment]
I published https://pub.dev/packages/ffi/versions/0.2.0-nullsafety.0

**Pull request merged**
